services:
  server:
    image: cosmtrek/air
    networks:
      - chungus
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      - POSTGRES_DATABASE_URL=postgres://postgres:chungusbunguswungus@postgresql:5432/db
      - REDIS_DATABASE_URL=redis://queue:6379/0
      - PORT=8080
    depends_on:
      - postgresql
      - queue

  postgresql:
    image: postgres
    networks:
      - chungus
    restart: unless-stopped
    shm_size: 128mb # recommended by docs, idk why
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chungusbunguswungus
      POSTGRES_DB: db
      PGDATABASE: db
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/

  queue:
    image: redis
    restart: unless-stopped
    networks:
      - chungus
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=chungusbunguswungus
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

  # adminer:
  #   image: adminer
  #   networks:
  #     - chungus
  #   restart: always
  #   ports:
  #     - 8080:8080

  # debug:
  #   image: busybox:latest
  #   command: sh
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - chungus


networks:
  chungus:
